name: dhbw_swe_mastermind_frontend
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^0.38.2
  http: ^0.12.0+2
  provider: ^3.1.0
  sembast_web: ^1.1.0+1
  path_provider: ^1.6.5
  package_info: ">=0.4.0+16 <2.0.0"
  flutter_markdown: ^0.3.4
  flutter_colorpicker: ^0.3.2
  connectivity: ^0.4.8+5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"
  pedantic: ^1.8.0
  effective_dart: ^1.2.0



flutter:
  uses-material-design: true

  assets:
    - assets/img/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/img/icon.png"
  adaptive_icon_foreground: "assets/img/icon-foreground.png"
  adaptive_icon_background: "assets/img/icon-background.png"
